mew_pipe_api_video:
    resource: "@MewPipeAPIVideoBundle/Resources/config/routing_rest.yml"
    prefix:   /api
    type:     rest

mew_pipe_api_user:
    resource: "@MewPipeAPIUserBundle/Resources/config/routing_rest.yml"
    prefix:   /api
    type:     rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

